In [6]:
import numpy as np

np.random.rand(5, 5)

array([[0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998],
       [0.92187424, 0.0884925 , 0.19598286, 0.04522729, 0.32533033],
       [0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451],
       [0.54269608, 0.14092422, 0.80219698, 0.07455064, 0.98688694],
       [0.77224477, 0.19871568, 0.00552212, 0.81546143, 0.70685734]])

In [3]:
np.random.seed(42)

In [ ]:
def linear_layer(input, d1, d2):
    out = input @ np.random.rand(d1, d2)

In [10]:
import torch

In [27]:
a = torch.rand((784, 10))

In [28]:
b = torch.ones(10)

In [30]:
a + b

tensor([[1.9466, 1.7256, 1.2597,  ..., 1.3359, 1.9041, 1.7468],
        [1.7700, 1.0561, 1.3516,  ..., 1.5009, 1.5269, 1.0142],
        [1.1566, 1.5628, 1.2256,  ..., 1.6972, 1.1102, 1.6321],
        ...,
        [1.6929, 1.3285, 1.7769,  ..., 1.2916, 1.4130, 1.3615],
        [1.6815, 1.2236, 1.2000,  ..., 1.4086, 1.5227, 1.6996],
        [1.0361, 1.1655, 1.1084,  ..., 1.5562, 1.2067, 1.7014]])

In [68]:
class myLinear(nn.Module):
    def __init__(self, input, out, bias=True):
        super().__init__()
        self.bias = bias
        self.in_features = input
        self.out_features = out
        
        self.w = torch.rand((input, out))
        self.bias_vector = torch.ones(10)
        
    def forward(self, x):
        if self.bias:
            return x @ self.w + self.bias_vector
        return x @ self.w
    
    def extra_repr(self):
        return f'in_features={self.in_features}, out_features={self.out_features}, bias={self.bias}'

In [69]:
my = myLinear(784, 10)

In [77]:
my

myLinear(in_features=784, out_features=10, bias=True)

In [70]:
a = torch.rand(1, 784)

In [71]:
my(a)

tensor([[198.6807, 192.7532, 194.0907, 194.1066, 191.0456, 193.8449, 193.0988,
         186.3689, 192.9310, 193.1070]])

In [72]:
class Mnist_Logistic(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = myLinear(784, 10)
        
    def forward(self, x):
        return self.linear(x)

In [73]:
model = Mnist_Logistic().cuda()

In [74]:
model

Mnist_Logistic(
  (linear): myLinear(in_features=784, out_features=10, bias=True)
)

In [75]:
model.linear

myLinear(in_features=784, out_features=10, bias=True)

# MNIST SGD